### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by sandervanhooft** [MantarayAR/space-kitty#19]

**Comment by idmontie** [comment]
Now that meteor 1.3 is out and stable, I was planning on updating it. The Apollo code seems important as well, so I'm waiting for that to have reactivity built into it. I've also been working with raw react and redux using graphql, so that's been where most of my time has been.

Happy to continue working on the project and accept prs as well!

**Comment by sandervanhooft** [comment]
@idmontie Great to hear you have some hands-on experience with graphql before adopting it.

I've put myself on the [mailing list](http://spacekitty.capsulecat.com). Would be great to be notified when spacekitty is upgraded with this features!

I'll be giving spacekitty a try to see if it fits my needs in its current state.
